import { Poppins, Roboto } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const myfont = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
});

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
});

export const metadata: Metadata = {
  title: "Class ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myfont.className}>
        {/* <div className={robotoFont.className}>This is header</div> */}
        {children}
      </body>
    </html>
  );
}